### ISSUE TITLE
spring boot starter does not configure watchdog

### ISSUE THREAD

**Issue by fogninid** [jpmsilva/jsystemd#1]
`watchdogPeriod` is not configured on the Systemd instance created by the spring boot starter, and it is not possible to activate.

Ideally no explicit configuration should be needed and the starter should just read [WATCHDOG_USEC](https://www.freedesktop.org/software/systemd/man/sd_watchdog_enabled.html#%24WATCHDOG_USEC) from the environment.

**Comment by jpmsilva** [comment]
Release 1.0.3 addresses this.
Thanks for bringing the issue to my attention.
