### ISSUE TITLE
Provide API for detecting if running under Systemd for non-spring apps

### ISSUE THREAD

**Issue by edgecase14** [jpmsilva/jsystemd#13]
Providing a similar function to internal APIs SystemdUtilities.isUnderSystemd() or SystemdNotify.usable() would be helpful for non-Spring/non-Tomcat apps.  I am actually running Jetty Embedded but am happy with a plain non-integrated implementation.

I noticed the Systemd.logStatus() method which is helpful, but I can't read the result programmatically.

Other than that, this is a great piece of work, thanks!

**Comment by jpmsilva** [comment]
The project is offered in two parts.

The com.github.jpmsilva.jsystemd:jsystemd-core package is meant to be used as you mentioned: not depending on Spring/Spring Boot or Tomcat (see the [documentation site](https://jpmsilva.github.io/jsystemd-site/versions/3.1.1/howto.html#regular-java-application))

If you import that package into your project, it will not bring anything from Spring or Tomcat. It can be integrated with any other type of Java based service, including Jetty.

The user facing side of the API is com.github.jpmsilva.jsystemd.Systemd, and it can be programatically instantiated through it’s builder class.

What additional functionality would be missing for your use case?

**Comment by edgecase14** [comment]
I do have it up and running... it seems to just do nothing when not running under Systemd, which is fine, and the logStatus() method informs the sysadmin or developer about what is happening, so no real problems.

I haven't run into a hard use case yet, but it might be nice to switch logging from console to log file when running under Systemd, this could also be done by application configuration which has other differences for development vs production.  I guess I'm just thinking out loud, for now.

**Comment by jpmsilva** [comment]
Hi @edgecase14 

jsystemd is designed to use slf4j as the logging facade.
Any API consumers can use any logging framework to control the logs (logback being the natural logging backend for slf4j). This way logging is not a direct concern of the jsystemd library, and you can use the configuration of your desired logging framework to redirect the log to a file if you so prefer.

The [logStatus](https://jpmsilva.github.io/jsystemd-site/versions/3.1.1/apidocs/com/github/jpmsilva/jsystemd/Systemd.html#logStatus()) method is provided to API consumers to call whenever they desire to output the status of the systemd integration to the log.
Look at the provided [Spring Lifecycle implementation](https://github.com/jpmsilva/jsystemd/blob/26a0adc0ca49cd5c672a3acc7c88ad4d9fc0be55/jsystemd-spring-boot-starter/src/main/java/com/github/jpmsilva/jsystemd/SystemdLifecycle.java#L45) as an example on how it can be used.

Do let me know if you run into any issues with the library.
