### ISSUE TITLE
The documentation does not indicate this

### ISSUE THREAD

**Issue by gomin1d** [jpmsilva/jsystemd#2]
This link has an example of a service:  
https://jpmsilva.github.io/jsystemd-site/versions/1.0.1/howto.html

```ini
[Unit]
Description=MyService
Requires=network.target
After=network.target
After=syslog.target

[Service]
Type=notify
WorkingDirectory=/opt/myservice
ExecStart=/opt/jdk1.8.0/bin/java -XX:+ExitOnOutOfMemoryError -Xms256M -Xmx512M -XX:+UseG1GC -jar /opt/myservice/myservice.jar
SuccessExitStatus=143
KillMode=mixed
TimeoutStopSec=10
TimeoutStartSec=30

[Install]
WantedBy=multi-user.target
```

But the important parameter is not specified, without which nothing worked for me.  
Namely this:
```ini
NotifyAccess=all
```

Please correct it in the documentation so that people like me do not waste time searching for the reason why it does not work.

:)

**Comment by jpmsilva** [comment]
Hi @lokha 

First of all, thanks for reporting this. I'm not sure why, but GitHub did not send me any notifications on your issue.

As documented in https://jpmsilva.github.io/jsystemd-site/versions/1.0.1/native-library.html you should only need to add `NotifyAccess=all` to your sevice unit when the native library (JNA) fails to load for some reason.
It would be preferable to use the native library instead, as the fallback implementation has some limitations.
Could you provide a log of the startup sequence of your Spring Boot application?

Thanks and best regards

**Comment by gomin1d** [comment]
@jpmsilva 
I am no longer busy with the project where I had a problem. and I can’t take the time to recreate the problem and throw you a log file.

I'm sorry, I don’t have time for this.
you can try to recreate the problem yourself or just close the issue

**Comment by jpmsilva** [comment]
No problem, that's fair.
I'll close this since I'm unable to replicate.
