### ISSUE TITLE
Spring Boot 3 support

### ISSUE THREAD

**Issue by anthares** [jpmsilva/jsystemd#9]
Hello,

We are using jsystemd spring boot starter for several years and it worked like a charm.

We are planning to migrate several apps to Spring Boot 3, and current release doesn't work.
(Mostly because of [removal of spring.factories](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files) file)
Is there a plan to release a Spring Boot 3 compatible version ?
Or does other users have a workaround to make it work ?

Thanks !
Best regards,

Nicolas

**Comment by jpmsilva** [comment]
Hello

Glad to hear that it has been of some use to someone else!

I am indeed working on a release targeting Spring Boot 3.
I was looking into the opportunity of moving the baseline JVM version to 17 to also streamline the communication with the systemd socket to the new UnixDomainSocketAddress, which might complicate the development process a bit.
This will hopefully enable jsystemd to remove the dependency on the net.java.dev.jna:jna dependency, which is what currently allows jsystemd to "talk" with systemd.

So at the time I cannot commit to a concrete timeline, but I expect it to come out sooner or later.

Best regards

**Comment by anthares** [comment]
Hello

Thank you for your answer !
Since activity was quite low on this project (no judgement here :) ), we were afraid it wont be updated.

Since Spring 6 requires Java 17, it's indeed a logical change.
We'll be looking forward for the updated version.

Best regards,

Nicolas

**Comment by jpmsilva** [comment]
Hi

Version 3.0.0 has just been released:

https://github.com/jpmsilva/jsystemd/releases/tag/version-3.0.0
https://jpmsilva.github.io/jsystemd-site/versions/3.0.0/

As expected, it moves the minimum supported versions of Java to 17, and Spring Boot to 3.
The new implementation based on UNIX domain sockets offers the most convenient integration (it is, after all, the way systemd expects to be called). This, in turn, allows the removal of other dependencies, chief among them, the jna library.
Do let me know if you find any issues.

Best regards

**Comment by anthares** [comment]
Hi !

Great news :)
Thank you for all the work done to make it compatible.
I'll share the news with my colleagues and we will test the new version.

Best regards

Nicolas
